[package]
name = "sn_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet = "0.11.0"
starknet-crypto = "0.7.0"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.4.0"